runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest
- name: lxml
  version: latest
- name: MySQLdb
  version: latest

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /static
  static_dir: static
- url: /.*
  script: timetable.app

